# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mockthis < Formula
  desc "Mock API endpoints for testing and development."
  homepage "https://mockthis.io"
  version "0.9.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.4/mockthis-cli_0.9.4_darwin_amd64.tar.gz"
      sha256 "ef57e22dbdde44415b4ed452ab79521d744745d06f2612f350133560104d6a4f"

      def install
        go install ./cmd/mockthis
      end
    end
    on_arm do
      url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.4/mockthis-cli_0.9.4_darwin_arm64.tar.gz"
      sha256 "f98e1c84c6906629600a107c657d99c968e0b39fed0348a4a71973f38ffc17ae"

      def install
        go install ./cmd/mockthis
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.4/mockthis-cli_0.9.4_linux_amd64.tar.gz"
        sha256 "108e0dd2075e1ccac465ba1f77f51d96b1433d40ab33bb9f203c3f4a2b0f5f3f"

        def install
          go install ./cmd/mockthis
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.4/mockthis-cli_0.9.4_linux_arm64.tar.gz"
        sha256 "b3372e9dca8cd28ee8fd64eb53e2f479a793cabb1424d034d417b9b3c039eef0"

        def install
          go install ./cmd/mockthis
        end
      end
    end
  end
end
