# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eagle < Formula
  desc "Eagle Image Optimization API CLI"
  homepage "https://github.com/nicobistolfi/eagle-image-api"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nicobistolfi/eagle-image-api/releases/download/v1.1.0/eagle-image-api_1.1.0_darwin_amd64.tar.gz"
      sha256 "8abe42d61e5ef4b5cf4d3828732835dd542f809bc76a58bdb7a39e9c8c9f7b5c"

      define_method(:install) do
        bin.install "eagle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nicobistolfi/eagle-image-api/releases/download/v1.1.0/eagle-image-api_1.1.0_darwin_arm64.tar.gz"
      sha256 "c3b89eaee8684aeb3148b96547bc38c8c903aae535ed3a887275a7ece6e15bec"

      define_method(:install) do
        bin.install "eagle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicobistolfi/eagle-image-api/releases/download/v1.1.0/eagle-image-api_1.1.0_linux_amd64.tar.gz"
      sha256 "8c1666eb6357653b77087fc072bdcbee345309004af452d7c83e9ee10faef9ac"
      define_method(:install) do
        bin.install "eagle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nicobistolfi/eagle-image-api/releases/download/v1.1.0/eagle-image-api_1.1.0_linux_arm64.tar.gz"
      sha256 "a1290d67ed0918953224f1cd79301b22fb43ca9fa2220d4d97d893f66c68307e"
      define_method(:install) do
        bin.install "eagle"
      end
    end
  end

  test do
    system "#{bin}/eagle --version"
  end
end
