# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mockthis < Formula
  desc "Mock API endpoints for testing and development."
  homepage "https://mockthis.io"
  version "0.9.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.5/mockthis-cli_0.9.5_darwin_amd64.tar.gz"
      sha256 "f8635b2973378d24a93bb45436a9d8c70378dcf065a8bb08c090fdfbff158195"

      def install
        go install ./cmd/mockthis
      end
    end
    on_arm do
      url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.5/mockthis-cli_0.9.5_darwin_arm64.tar.gz"
      sha256 "2f99097a5ab0c81639020094f49f0cb47e8222e6f0334564abbea6b35eb23d3c"

      def install
        go install ./cmd/mockthis
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.5/mockthis-cli_0.9.5_linux_amd64.tar.gz"
        sha256 "019fe988f47a6aa26bf2ae6feeb1b71be6f9af0c16ed5066dc141a3027494aac"

        def install
          go install ./cmd/mockthis
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nicobistolfi/mockthis-cli/releases/download/0.9.5/mockthis-cli_0.9.5_linux_arm64.tar.gz"
        sha256 "89dda4666420086b3656e91c0346d0d0c6ead25806d74e172c8cf5dbf1fa8d56"

        def install
          go install ./cmd/mockthis
        end
      end
    end
  end
end
